apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ssp-dev-as2-eks
  region: ap-southeast-2

managedNodeGroups:
  - name: ssp-dev-as2-eks-ng-mgmt
    instanceType: c5.large
    availabilityZones:
      - ap-southeast-2a
      - ap-southeast-2c
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: ds07715
    labels:
      role: worker
    privateNetworking: true
    tags:
      nodegroup-role: "worker"
      ServiceName: SSP
      Name: ssp-dev-as2-eks-ng-mgmt
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
#    ami: xxx
#    maxPodsPerNode: 110
    instancePrefix: ssp-dev-as2
    instanceName: ec2-mgmt
